"""Cached_data

Revision ID: 9d531d9a8f9a
Revises: 5ab50dd5b5b1
Create Date: 2024-04-02 10:14:33.471888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d531d9a8f9a'
down_revision: Union[str, None] = '5ab50dd5b5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('query_result', sa.String(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_data')
    # ### end Alembic commands ###
