"""del author

Revision ID: e295289fcb2c
Revises: d1b1a0ab03b2
Create Date: 2024-04-01 21:33:05.224698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e295289fcb2c'
down_revision: Union[str, None] = 'd1b1a0ab03b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
